### ISSUE TITLE
documents with \include fail

### ISSUE THREAD

**Issue by FrankMittelbach** [cereda/checkcites#6]
If a LaTeX document contains \include statements then the main `.aux` file will reference sub-aux files via lines like
```
\@input{ch-intro.aux}
```
Would be nice if those get handled because espcially in larger documents the script is useful and there you often have include-structures

**Comment by cereda** [comment]
Frank, thank you for the suggestion, I completely forgot about `\include`! I will mark this as a feature for the next update.

**Comment by felker** [comment]
This may be an old/inactive issue, but I will leave my experience here for others who come to this with the same problem

The script call `checkcites thesis.aux` was working when I was using `\import{ch-intro/chapter-intro}` in my main document, `thesis.tex`. I switched to using `\include{ch-intro/chapter-intro}` and it stopped  picking up the `.aux` subfiles. My workaround was just to feed all `.aux` files to the script, via `checkcites **/*.aux`

**Comment by FrankMittelbach** [comment]
@cereda  Paulo, any update on this?

**Comment by cereda** [comment]
@felker @FrankMittelbach Hi friends, I will try to work on this issue later on today. I really forgot about these issues, given the stress and pressure on thesis writing back then, but now I have no excuse. :wink:

Sorry for the delay. I have an idea for a fix, let's see if I can make it work...

**Comment by felker** [comment]
I started using this tool because I am writing my own thesis right now. It has been quite helpful; thanks for sharing and maintaining it! 👏

**Comment by cereda** [comment]
@FrankMittelbach Frank, I might need your expert opinion. :wink:

First things first, I found the lines in which I should include the extraction of other auxiliary files. I might need to change the overall logic, but it is surely doable. So far, so good.

However, when I did some tests with an actual document, I found some unexpected behaviour regarding side effects provoked by certain packages. Namely, `abnt2cite` seems to pass some options to the backend through citation keys (at least, that's my reading), e.g:

```tex
\citation{abnt-url-package=url}
```

Also, the aforementioned package also adds its default options as a bibliograhy file (namely, `abntex2-options`), referenced in `\bibdata` alongside the actual reference:

```
\bibdata{abntex2-options,myrefs}
```

This also brings us to the issue raised by ulrike (@u-fischer) in #8, as `checkcites` does not use `kpathsea` to find bibliographies in the TeX tree, so the lookup for `abntex2-options` also fails. Since BibTeX, as far as I understand, is a relaxed format, `abntex2` exploits custom types as `@ABNT-options` to add options. In #7, I simply added `string` to the list (table) of discarded key entries, but it seems there is a lot more to be added.

I am more than glad to rewrite the tool to make it better and more useful to the general public, but I might need some opinions on how to tackle these nuisances. I understand that, in this particular scenario, it's a package-based exploit, but I am not sure how others interfere with the `.aux` writing.

Just to cross the thought out my mind, a cyclic dependency in `\include`'s is most improbable, right? Unless of course someone very naughty (definitely _not_ @davidcarlisle) crafts a set of mutually recursive auxiliary files. Given that the `.aux` is generated by the engine itself, the resulting `.aux` should let the tool terminate...

Cheerio!

**Comment by u-fischer** [comment]
`\include` can't be nested, so there is no danger that mean people break your script. 

ieeetran too has some "option passing system": https://tex.stackexchange.com/a/487599/2388. 

My main interest is with biblatex and that there bib's are found with kpathsea so I wouldn't mind much if some curious setups of bibtex styles gives false positives ;-). You can always document such problematic cases.

**Comment by FrankMittelbach** [comment]
hi Paulo

> @FrankMittelbach <https://github.com/FrankMittelbach> Frank, I might 
> need your expert opinion. 😉

not sure I have one

> However, when I did some tests with an actual document, I found some 
> unexpected behaviour regarding side effects provoked by certain 
> packages. Namely, |abnt2cite| seems to pass some options to the backend 
> through citation keys (at least, that's my reading), e.g:

I must confess I never heard of that package (or any other package using 
such anapproach).

quick check suggests it comes from your part of the world, correct? the 
only documentation I could find was abnt-doc but that wasn't very 
illuminating for me due to my lack of language knowledge. No abnt2cite 
anywhere though
> 
> \citation{abnt-url-package=url}

guess that basically means that either your code doesn't work for that 
package or that you provide some special support for it (if it is 
well-used in your country) like ignoring certain citations that are 
really option settings as far as I understand
> 
> Also, the aforementioned package also adds its default options as a 
> bibliograhy file (namely, |abntex2-options|), referenced in |\bibdata| 
> alongside the actual reference:
> 
> |\bibdata{abntex2-options,myrefs} |
> 
> This also brings us to the issue raised by ulrike (@u-fischer 
> <https://github.com/u-fischer>) in #8 
> <https://github.com/cereda/checkcites/issues/8>, as |checkcites| does 
> not use |kpathsea| to find bibliographies in the TeX tree, so the lookup 
> for |abntex2-options| also fails. 

using kapthsea would certainly something that should be done, after all 
most TeX installations contain a good number of.bib files with useful 
data (around typesetting TeX and CS) eg Beebe's collections and more

but getting kapthsea to work should not be a problem really, would it?

> Since BibTeX, as far as I understand, 
> is a relaxed format, |abntex2| exploits custom types as |@ABNT-options| 
> to add options. In #7 <https://github.com/cereda/checkcites/issues/7>, I 
> simply added |string| to the list (table) of discarded key entries, but 
> it seems there is a lot more to be added.

maybe, but their defaults aren't that many and if it is the only package 
that does this kind of thing ...

> I am more than glad to rewrite the tool to make it better and more 
> useful to the general public, but I might need some opinions on how to 
> tackle these nuisances. I understand that, in this particular scenario, 
> it's a package-based exploit, but I am not sure how others interfere 
> with the |.aux| writing.

oh aux files a messed around by many packages unfortunately. However, 
see it this way. bibtex uses a simple mechanism to extract data from the 
aux file andif you follow this method then your command works as long as 
bibtex would be able to work with the file

and that is looking for

\citation \bibdata and \bibstyle and \@input and ignore the rest
> 
> Just to cross the thought out my mind, a cyclic dependency in 
> |\include|'s is most improbable, right? Unless of course someone very 
> naughty (definitely /not/ @davidcarlisle 
> <https://github.com/davidcarlisle>) crafts a set of mutually recursive 
> auxiliary files. Given that the |.aux| is generated by the engine 
> itself, the resulting |.aux| should let the tool terminate...

include files aren't nested (and nobody yet tried to make that happen, 
so a simple 2-level approach would work (and otherwose some input stack 
would work but as I said there are only 2 levels)

cheers
frank

**Comment by cereda** [comment]
@FrankMittelbach @u-fischer Thank you very much for the details, friends!

**Comment by cereda** [comment]
Support for automatic inclusion of auxiliary files via `\include` statements is now implemented. :wink:

**Comment by FrankMittelbach** [comment]
@cereda thanks, but that doesn't magically get it to CTAN (which is where it has to be to get into the distributions :-) )

**Comment by FrankMittelbach** [comment]
just tested it and it seems to work fine
